In [1]:
import torch

import numpy as np

import time
import model_v2 as cnnmodel







In [2]:
input1=torch.rand(3,12,50,dtype=torch.float64)
input3=
print input3.size()
input2=torch.rand(12,dtype=torch.float64)


SyntaxError: invalid syntax (<ipython-input-2-75f510e56805>, line 2)

In [ ]:
model = cnnmodel.CNNv2()
model =model.double()


In [ ]:
model.load_state_dict(torch.load('data/model2_params2_03.pkl'))


In [3]:
model.eval()


NameError: name 'model' is not defined

In [4]:
output = model(input1,input2)


NameError: name 'model' is not defined

In [ ]:
output

In [ ]:
output = torch.reshape(output, [2, 12, 50])

In [ ]:
output[1]

In [ ]:
print output[1].size()

In [ ]:
output[2]

In [ ]:
output[0]

In [ ]:
output[1]*50

In [ ]:
torch.sum(output[0][1][:])

import torch.nn as nn


In [17]:
import torch
import torch.nn as nn


In [77]:
n=torch.randn(2,6,3)
m=nn.functional.softmax(n,dim=0)

In [78]:
n

tensor([[[-0.3529,  0.8270, -0.5694],
         [-1.6730,  0.6734,  0.2990],
         [ 0.1333,  0.4385, -0.9663],
         [-1.8208, -0.1070, -0.8407],
         [-0.8706, -0.8590, -0.0367],
         [ 0.9523, -0.4823, -0.4585]],

        [[ 1.3278, -1.3125,  0.5913],
         [ 0.7104, -0.8764, -1.9533],
         [ 0.4882, -0.5091,  0.6954],
         [ 2.6128,  0.1367, -0.7906],
         [-0.9131,  0.4310, -0.6933],
         [-0.1925, -0.3021, -1.9894]]])

In [79]:
m


tensor([[[0.1570, 0.8947, 0.2385],
         [0.0844, 0.8249, 0.9048],
         [0.4122, 0.7206, 0.1595],
         [0.0117, 0.4394, 0.4875],
         [0.5106, 0.2159, 0.6585],
         [0.7585, 0.4551, 0.8221]],

        [[0.8430, 0.1053, 0.7615],
         [0.9156, 0.1751, 0.0952],
         [0.5878, 0.2794, 0.8405],
         [0.9883, 0.5606, 0.5125],
         [0.4894, 0.7841, 0.3415],
         [0.2415, 0.5449, 0.1779]]])

/home/jing/anaconda2/envs/py27torch/lib/python2.7/site-packages/ipykernel_launcher.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  """Entry point for launching an IPython kernel.


tensor([0.3014, 0.1395, 0.5591])

In [14]:
output=m(input)

/home/jing/anaconda2/envs/py27torch/lib/python2.7/site-packages/ipykernel_launcher.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  """Entry point for launching an IPython kernel.


In [72]:
class net(nn.Module):
    def __init__(self):
        super(net, self).__init__()
        self.fc=nn.Linear(125, 25)              


    def forward(self, x):
        x2=self.fc(x)
        y=nn.functional.softmax(x2,dim=0)       
        
        return y

NET=net()

In [73]:
input=torch.randn(125)

In [74]:
y=NET(input)

tensor([0.0371, 0.0205, 0.0510, 0.0418, 0.0142, 0.0304, 0.0417, 0.0807, 0.0618,
        0.0742, 0.0174, 0.0367, 0.0586, 0.0248, 0.0220, 0.1273, 0.0290, 0.0123,
        0.0236, 0.0158, 0.0303, 0.0450, 0.0358, 0.0145, 0.0535],
       grad_fn=<SoftmaxBackward>)